### ISSUE TITLE
Componentes sociales (Facebook/twitter)

### ISSUE THREAD

**Issue by NazarenoL** [DemocraciaEnRed/vos-que-propones#10]
Dada la importancia que puede tener social media para la difusión de una herramienta como esta, es importante hacer uso de los componentes que las dos principales redes sociales brindan.

Lo primero y fundamental es agregar los og tags (og:title, og:image y og:description), de forma de mejorar el snippet mostrado en facebook:

![screen shot 2015-04-22 at 3 57 53 pm](https://cloud.githubusercontent.com/assets/1238114/7282740/623d04c0-e908-11e4-843a-231163521ec7.png)

En una segunda instancia, una buena opción seria agregar al pie de página los botones provistos por estas redes:
![ajax_social](https://cloud.githubusercontent.com/assets/1238114/7282771/96ccce28-e908-11e4-9762-518a3a9da2f6.png)

**Comment by fvilledary** [comment]
Las etiquetas og ya las agregué, pero parece que facebook ya lo cacheo mal :/ esperemos que se actualice

**Comment by fvilledary** [comment]
Hoy a la tarde, cuando llegue a mi casa, pensaba poner botones de share y tweet en cada propuesta, candidato y partido.
Para eso hice que la url se actualice como lo hace.

**Comment by fcaivano** [comment]
Podes usar esta herramienta en el futuro para borrara el cache de open graph:

https://developers.facebook.com/tools/debug/

**Comment by fcaivano** [comment]
Podes usar esta herramienta en el futuro para borrar la cache de open graph:

https://developers.facebook.com/tools/debug/

Después de poner la url y darle a debug, le das a "Fetch new scrape information" y suele acelerar la actualización.

**Comment by fvilledary** [comment]
Buenísimo, gracias

**Comment by NazarenoL** [comment]
Ups! Se ve que lo subiste en el tiempo que paso entre que lo chequié y postié esto!

PD: Hicieron los cambios directos en prod? No lo veo en el commit log:
https://github.com/DemocraciaEnRed/vos-que-propones/blob/master/index.html

**Comment by fvilledary** [comment]
Acabo de probar y ya pone bien todos los datos cuando compartis

**Comment by fvilledary** [comment]
Si, hice los cambios así nomas porque estoy en el trabajo y tengo
limitaciones acá. Hoy comiteo todo cuando llego a mi casa

**Comment by NazarenoL** [comment]
@fvilledary está perfecto! preguntaba por saber si era asi o se me estaba escapando algo, y queria entenderlo! :) 
:+1:  gracias! Cierro este issue
