### ISSUE TITLE
Fuentes

### ISSUE THREAD

**Issue by martinvol** [DemocraciaEnRed/vos-que-propones#11]
Linkear las fuentes de las propuestas. en las mismas.

**Comment by fvilledary** [comment]
Denme alguna idea como se podría mostrar la fuente, sin que ocupe mucho espacio

**Comment by martinvol** [comment]
![prop](https://cloud.githubusercontent.com/assets/698027/7719380/e928eab4-fe96-11e4-8658-f1567719b3c1.png)
EL expansible está siempre al final, como un texto más de la propuesta, ocupa siempre una palabra, salvo que el usuario cliquee y se expande abajo.

De más está decir que hay que pensar como se vería, solo marco lugares en la imagen.

**Comment by fvilledary** [comment]
Ok. Mañana lo hago así.

**Comment by fvilledary** [comment]
Listo. queda cerrado este tema.

**Comment by fvilledary** [comment]
Listo. Queda cerrado este tema.
