### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by NazarenoL** [DemocraciaEnRed/vos-que-propones#12]
Si bien desde el mismo sitio se incita a hacer un fork, no encontré información sobre que licencia tiene. 

Técnicamente, y según los faqs de Github, al no haber ninguna licencia especificada, tienen valor las leyes "comunes" de licencia, por ende, el autor tiene copyright y derechos sobre la app; lo que anularía un poco el sentido del fork, mas allá de poder aportar con un pull request.

Sería ideal agregarlo al Readme :)

**Comment by fvilledary** [comment]
Yo no entiendo de esas cosas burocráticas. El que quiera que lo haga.

**Comment by NazarenoL** [comment]
El tema es que hay muchas licencias distintas, y tienen ciertas diferencias mas allá del nombre y como esté escrito. Hay muchas decisiones como para mandarlo yo desde un pull request.

Ser completamente permisivo en cuanto a forks, o exigir que se cite la app original/democracia en red? Exigir que los forks sigan siendo open source? Permitir o no que alguien tenga fines comerciales (con publicidad, por ejemplo) en su fork?

Por lo que veo, en otros proyectos de Democracia En Red fueron por la licencia MIT, una de las mas abiertas. (Agregada por @gvilarino , que capaz puede dar algún tip acá)

https://github.com/DemocraciaEnRed/democraciaenred.github.io/blob/master/LICENSE

**Comment by martinvol** [comment]
A mi me parece bien la MIT, si nadie se opone vamos con esa.

**Comment by gvilarino** [comment]
+1 MIT

Pueden copypastear [la que tenemos en DemocracyOS](https://github.com/DemocracyOS/app/blob/development/LICENSE.txt)

Si quieren más detalles visiten [choose a license](http://choosealicense.org/) pero para mí MIT va bárbaro.

**Comment by gvilarino** [comment]
Me [lombardicé](http://uqbar-wiki.org/index.php?title=Lombardizaci%C3%B3n) y lo hice: https://github.com/DemocraciaEnRed/vos-que-propones/pull/15
