### ISSUE TITLE
¿Otras provincias o localidades?

### ISSUE THREAD

**Issue by ramasilveyra** [DemocraciaEnRed/vos-que-propones#18]
Tienen pesado dar soporte a las propuestas de candidatos de otras provincias o localidades?

**Comment by juandimaio** [comment]
Estamos pensando y trabajando en eso. Puede que hagamos versiones de otras provincias con ayuda de gente de ahí pero todavía no hay nada decidido.

**Comment by MattEsmay** [comment]
Yo quiero implementarlo en el Chaco, las PASO son el próximo 24 de Mayo. Tengo servidor y puedo registrar el sitio, también puedo (creo) implementarlo. ¿Necesito algo más? ¿Permiso alguno? (entiendo que no necesariamente) Porque podría empezar esta semana. ¡Saludos!

**Comment by fvilledary** [comment]
En estos momentos estamos mejorando un poco el sistema, para más facilidad
de carga de datos y más fácil implementación. En una semana va a estar
listo y creo que ahí sería mejor para ustedes implementarlo. Por el momento
lo ideal sería buscar todas las propuestas de los candidatos y tenerlas
listas para cargar.

**Comment by MattEsmay** [comment]
Dale, sí. Podríamos ir viendo eso. Seguimos hablando!

**Comment by gvilarino** [comment]
Se me ocurre que si @MattEsmay tiene un server nosotros lo que podríamos hacer es facilitar un `chaco.queproponen.com.ar` como para no intentar instalar un nombre nuevo (que siempre cuesta mucho más de lo que uno cree). Hacer algo como `queproponen.com.ar/chaco` es más costoso porque habría que alterar la app para que soporte estas redirecciones.

Igualmente son ideas; nada concreto.

**Comment by ramasilveyra** [comment]
Me sumo, yo quiero hacer lo mismo que @MattEsmay pero para Entre Ríos, también tengo server. Voy a estar a la espera de los nuevos cambios. Lo que propone @gvilarino me parece genial, trabajar con subdominios de `queproponen.com.ar` creo que es la mejor forma para dar una imagen unificada, hasta incluso mover el contenido actual a `caba.queproponen.com.ar` y dejar `queproponen.com.ar` como landin page con enlaces a los `queproponen` de todas las entidades federales (provincias y CABA) de la Argentina.

**Comment by fvilledary** [comment]
Estábamos pensando en hacer una landing page ya que se estaban por unir los
pares de Santa Fe y La Rioja. Ahora que ya seríamos 5 con mucha más razón!

**Comment by gvilarino** [comment]
Ojo, creo que es la solución más sencilla y con menos laburo necesario. Si vamos a hacer algo muy integrado quizás sí tiene sentido hacer las cosas como subrutas de la ppal. Todo depende del laburo que se quiera hacer.

**Comment by MattEsmay** [comment]
Yo estoy totalmente de acuerdo con lo de hacer un subdominio `chaco.queproponen.com.ar`

**Comment by MattEsmay** [comment]
Chicos, pregunta: Disponemos de un CMS o algo para cargar los datos o los iríamos cargando en `Propuestas.js` ?

**Comment by fvilledary** [comment]
En estos momentos estoy trabajando en un admin para poder cargar los datos
más fácilmente.
Hice unos cambios ya que todavía no los subí al repo, pero en la página las
cosas ya se están cargando desde una base de datos, no desde Propuestas.js

**Comment by gvilarino** [comment]
Github en cierta forma es un CMS, si tenés la data hardcodeada. Con github y un travis sencillo podés tener autodeploy a producción on commit y santo remedio.

**Comment by fvilledary** [comment]
Igual, como digo, la idea es que ya no se cargue desde ese archivo, sino
desde una base de datos usando PHP y ajax

**Comment by gvilarino** [comment]
PHP y Ajax :miedo:

**Comment by martinvol** [comment]
@MattEsmay 
@fvilledary 
Y si les replicamos el sitio en /chaco y ponen las propuestas en el .js? Tengo entendido que se les vienen las elecciones encima.

Habría que ver como hacemos con el branding del partido, son libres de usar el código para lo que quieran, pero yo lo tomaría como un muy buen gesto si lo dejan tal cual está. Me gustaría ver que pensás al respecto Matt, esta sería una buena oportunidad para fundar el nodo chaqueño del partido :)

**Comment by gvilarino** [comment]
Yo creo que si se hace en /chaco (por ende, en nuestro codebase) sí o sí tiene que ser con el branding del PDR. Si es en otro server (un fork) pueden hacer lo que usten mientras hagan referencia a queproponen.com.ar (atribución, onda Powered by QueProponen o PartidoDeLaRed)

**Comment by fvilledary** [comment]
Si quieren usar /chaco o /entrerios:
- Si en la ciudad donde se hace tiene un PDR, entonces los Likes y Follow
  de la izquierda irían para ese PDR si es que tuvieran facebook y twitter,
  de otra forma al PDR de CABA.
- El banner de arriba aparece por geolocalización. Si el PDR de esa ciudad
  tiene una página de afiliación, lo agregamos como opción a mostrar, siempre
  dependiendo de la geolocalización del usuario.
- El footer mostrará el branding del PDR CABA.
- Yo me encargo de la implementación y luego les pasaré un usr y pass a la
  administración de cada uno para que puedan cargar toda la data (partidos,
  candidatos, propuestas)
- En el 'Acerca de' aparecerá como desarrollador el PDR de CABA y ustedes
  (o el PDR de esa ciudad) como colaboradores y encargados de la data.

**Comment by fvilledary** [comment]
@ramasilveyra seguís con la idea de querer implementarlo? Si es así, mandame un mail.

**Comment by ramasilveyra** [comment]
@fvilledary ahí te mando.

**Comment by LeonardoSalvucci** [comment]
Hola a Todos, me interesa sumarme ya que la propuesta que ustedes vienen desarrollando es lo que hace tiempo me está dando vueltas fomentar. Soy de Rosario y estaba buscando la manera de realizar el queproponen para los intendentes de aquí. Actualmente estoy en la etapa inicial, pero creo que puedo lograr implementar un rosario.queproponen.com.ar. Soy profesional de IT por lo que las cuestiones técnicas puedo resolverlas. En que etapa está la implementación de subdominios?
Quedo atento a toda novedad.
Saludos y confiemos... el camino está por acá.

**Comment by indiofran** [comment]
hola leandro, te comento que estamos muy avanzados en ese tema(En la recta final). Solo falta gente que lo trabaje.
Vos quisieras hacerlo a la par nuestra. O queres desarrollar tu propio Queproponen(un fork)???

**Comment by LeonardoSalvucci** [comment]
Mi idea es trabajar a la par de ustedes, si pueden adelantarme que recursos es necesario me pongo en marcha para empezar cuanto antes a trabajar.

**Comment by indiofran** [comment]
Como habrás visto tenenos un sistema de admin, muy fácil de usar para cualquier persona.
Solo necesitamos la recopilación de los candidatos y sus propuestas. 
Ya tenemos un que proponen santa fe. Vos lo querés hacer a nivel rosario?

**Comment by LeonardoSalvucci** [comment]
Efectivamente, mi idea es hacerlo para Rosario. No se si hay pares a nivel Ciudad para trabajar juntos, el que quiera sumarse bienvenido sea. Yo empecé a recopilar algunas propuestas de los 5 que figuran como candidatos oficiales en las páginas de santafe.gov.ar.
Y por Santa Fe, si nos hablamos, podemos trabajar para recopilar datos de los cargos provinciales.

**Comment by indiofran** [comment]
Perfecto leandro, vamos a trabajar ahora en la creación del subdominio. Así ya te podes poner en marcha para que puedas empezar a trabajar en ella. Mandale un mail. Fede así te el manda toda la data federico.villedary@gmail.com

**Comment by gvilarino** [comment]
@indiofran sugiero publiquen en el `README.md` los pasos a seguir para alguien que quiera tener su versión de este website, y fundamentalmente los pasos a seguir para tener un subdominio de `queproponen.com.ar`

**Comment by martinvol** [comment]
@gvilarino Fede hizo eso hoy, hay un mail en el que cada interesado puede postularse para una determinada provincia/ciudad.
Cierro el issue, aunque todavía esperamos respuestas de los que se propusieron y todavía no nos contactaron.
