### ISSUE TITLE
Página por partido/frente

### ISSUE THREAD

**Issue by fvilledary** [DemocraciaEnRed/vos-que-propones#2]
Cuando se aprete un partido/frente, mostrar un header del partido y a continuación sus candidatos y sus propuestas.

**Comment by juandimaio** [comment]
Me gusta la idea pero creo que también podríamos ahorrar espacio en la home mostrando directamente los candidatos; en vez de saturar de información el sitio con todos los partidos.

**Comment by fvilledary** [comment]
Creo que ver los partidos es importante, más que nada para ver la relación que tienen entre sus propios candidatos, cuanto se diferencian sus propuestas.
