### ISSUE TITLE
Calidad del sitio

### ISSUE THREAD

**Issue by juandimaio** [DemocraciaEnRed/vos-que-propones#20]
Considero que estamos recargando demasiado el sitio. Haber puesto una barra flotante con el objetivo de conseguir más afiliaciones me parece invasivo; no me parece mal pero quizá se podría repensar de qué manera y en qué lugar del sitio hacerlo. 
Otro punto que critico es la presencia de los botones flotantes para dar me gusta y seguir al PDR. Con el mismo argumento que antes, podríamos pensar otra forma de hacerlos presentes o mejorar el diseño de los que están.
Estos aspectos que menciono me parecen importantes porque siento que al agregar nuevos elementos al sitio lo estamos recargando y quizá, desviando de la estética con la que fue presentado.

**Comment by fvilledary** [comment]
yo pienso más o menos lo mismo, pero esas cosas nos vienen bien. pensando en el formato de la página, la única forma de poner cosas adicionales es arriba o abajo. abajo nadie llega. lo de los botones de facebook y twitter no me parece que invada mucho, ya que está bien pegado al borde, y en mobile desaparece.

**Comment by ignacionelson** [comment]
Creo que esa barra superior le saca parcialidad al sitio. Le agrega un toque partidario a algo que básicamente es una herramienta neutral. Los logos de PDR están lógicamente por ser desarrolladores/impulsores.

**Comment by fvilledary** [comment]
La barra de arriba ya no es tan invasiva.

**Comment by gvilarino** [comment]
No me parece mal en absoluto -sino todo lo contrario- que se haga presencia, mención y solicitud de apoyo al Partido de la Red. Éste es un proyecto que nace desde el PDR para toda la ciudadanía; y por eso una de las cosas en las que está bueno hacer énfasis.

Dicho de otra manera _esta herramienta tiene una clara intención política y **eso está bien**_. No decirlo u ocultarlo es incluso peor porque (al menos desde el equipo de trabajo de que ideó y desarrolló esta herramienta) sería ser hipócrita.

Pero ojo, también nos encanta que otras personas utilicen esta herramienta si quieren, sin necesidad de hacer mención al PDR; por eso justamente es licencia MIT y pueden hacer sus forks e implementaciones customizadas.

**Comment by martinvol** [comment]
@ignacionelson La barra es solo un aviso, no tiene mucha diferencia con el resto de los demás logos.

@jana95 Por favor evitemos las criticas genéricas, si crees que hay cosas que recargan la página y a su vez son necesarias, plantiemos una alternativa, sino estás cosas nunca llegan nada.

**Comment by juandimaio** [comment]
@martinvol La crítica era en realidad para el header anterior, ahora está mucho mejor. Después de juntarnos y empezar a definir algunas cosas a futuro se implementó este nuevo header, donde la barra que invita a afiliar es mucho más discreta ;)
