### ISSUE TITLE
Cambiar nombre de repositorio

### ISSUE THREAD

**Issue by ramasilveyra** [DemocraciaEnRed/vos-que-propones#21]
Cambiar el nombre del repositorio a `queproponen`.

**Comment by juandimaio** [comment]
Concuerdo, creo que la plataforma se llama "¿Qué proponen?", es la pregunta que titula al sitio web. Y además con la difusión que tuvo, ya fue reconocido por la gente con ese nombre.

**Comment by gvilarino** [comment]
@martinvol @fvilledary denme el ok y lo cambio

**Comment by martinvol** [comment]
No hay problema por mi, naturalmente tomó ese nombre.

**Comment by fvilledary** [comment]
Si, cambialo

**Comment by gvilarino** [comment]
done
