### ISSUE TITLE
Página por candidato

### ISSUE THREAD

**Issue by fvilledary** [DemocraciaEnRed/vos-que-propones#3]
Cuando se aprete un candidato, mostrar un header del candidato y a continuación sus propuestas.

**Comment by juandimaio** [comment]
Estaba pensando algo más animado e intuitivo que te permita leerlas sin salir de la home. Quizá para las definitivas se pueda implementar.

**Comment by fvilledary** [comment]
Siendo tantas las propuestas por candidato, me parece lo mejor aislar lo más que se pueda la información en pantalla, así la persona no se pierde.
Igualmente es bastante dinámico lo que hice, ya que nunca se recarga la página. simplemente se cargan unos u otros datos en un mismo contenedor.
