### ISSUE TITLE
[Consulta] Dump de las propuestas

### ISSUE THREAD

**Issue by Nullpo** [DemocraciaEnRed/vos-que-propones#30]
Buenas!

¿Tienen algun dump publico de las propuestas hechas?

Un par de conocidos los acusan de ser de izquierda, porque siempre les sale que su candidato debe ser de izquierda :P, y queriamos analizar todas las propuestas que hay para ver si faltan algunas (y proponerlas, obvio).

Muchas graicas!

**Comment by fvilledary** [comment]
Todas las propuestas de los candidatos están en
caba.queproponen.com.ar/propuestas. Las propuestas son sacadas de los
canales oficiales de los candidatos, ya sea página web propia, facebook o
twitter. Eso lo podes constatar desde el link [fuente] que tiene cada
propuesta. No ponemos propuestas que no sean exclusivamente de ese tipo de
canales (lease diarios, blogs, etc.)

**Comment by Nullpo** [comment]
Excelente, mil gracias! :D
