### ISSUE TITLE
Actualizar el thumbnail para Facebook card

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/vos-que-propones#32]
Está viejito, es el de las PASO
![screen shot 2015-10-14 at 4 09 27 pm](https://cloud.githubusercontent.com/assets/2538465/10495411/1835db68-7292-11e5-840b-2d7ddcc1715a.png)

**Comment by fvilledary** [comment]
La imagen la cambié hace unos días. Es problema de Cache.

**Comment by fvilledary** [comment]
La imagen la cambié hace unos días. Es problema de Cache.
