### ISSUE TITLE
No se carga el contenido en Firefox

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/vos-que-propones#33]
Latest (v41 inclusive). Varios OSs

![12168656_10153707403363343_464582240_o](https://cloud.githubusercontent.com/assets/2538465/10495435/3cac7b64-7292-11e5-91c5-c3cecf992847.jpg)

Veo un trace:
`TypeError: categorias is null` en `javascript.js@151`

```
case contenedores.CATEGORIAS:
    categorias.forEach(function(cat) {
    MostrarCategoria(0, cat);
});
```

**Comment by fvilledary** [comment]
Resuelto

**Comment by gvilarino** [comment]
:tada:
