### ISSUE TITLE
Mal las categorías

### ISSUE THREAD

**Issue by martinvol** [DemocraciaEnRed/vos-que-propones#7]
Peguen las correcciones.

**Comment by felipemuni** [comment]
Carlos Oviedo - FPV

Propuesta("Plan para resolver la crisis habitacional","Estructura estatal capaz de planificar y ejecutar políticas públicas de vivienda y hábitat que tiendan a resolver la crisis habitacional local: Ministerio de vivienda y hábitat; Banco de vivienda y hábitat (para centralizar y administrar los fondos necesarios); unidades comunales, donde los ciudadanos participen en pos de construir soluciones viables para resolver la problemática habitacional; Instituto de Registro de Inmuebles, donde se observen casos de ociosidad, cobrándoseles altos impuestos; Polo Centralizado de Monitoreo y Régimen de Selección de Aspirantes, para transparentar los procesos de adjudicación de viviendas construidas.", temas.VIVIENDA, 0, 5)
Propuesta("Garantizar la accesibilidad, universalidad, gratuidad y excelencia del servicio de salud pública de la Ciudad.", "", temas.SALUD, 0, 5),
Propuesta("Participación activa del Estado en cuanto a conducir, regular y acreditar al Sistema de Salud de la Ciudad en forma integral (sector público estatal, seguridad social y privado).", "", temas.SALUD, 0, 5),
Propuesta("Producción pública de medicamentos.", "", temas.SALUD, 0, 5),
Propuesta("Creación del Instituto de Fiscalización y Control Sanitario.", "", temas.SALUD, 0, 5),
Propuesta("Creación del Instituto de Biotecnología e Investigaciones Científicas.", "", temas.SALUD, 0, 5),
Propuesta("Creación del Sistema de Emergencia Unificado.", "", temas.SALUD, 0, 5),
Propuesta("Recuperación de los centros culturales y cines de barrio.", "", temas.SOCIEDAD, 0, 5),
Propuesta("Fomento y fortalecimiento de la cultura popular, con el objetivo de recuperar el papel protagónico y creativo del Pueblo.", "", temas.SOCIEDAD, 0, 5),
Propuesta("Protección del patrimonio cultural de la Ciudad.", "", temas.SOCIEDAD, 0, 5),

**Comment by felipemuni** [comment]
Propuesta("Recuperación de los centros culturales y cines de barrio.", "", temas.SOCIEDAD, 0, 5),
Propuesta("Fomento y fortalecimiento de la cultura popular, con el objetivo de recuperar el papel protagónico y creativo del Pueblo.", "", temas.SOCIEDAD, 0, 5),
Propuesta("Protección del patrimonio cultural de la Ciudad.", "", temas.SOCIEDAD, 0, 5),

**Comment by felipemuni** [comment]
Horacio Rodriguez Larreta

Propuesta("Acompañar el crecimiento de los chicos desde el embarazo hasta los primeros años de vida", "Para generar más oportunidades en la Ciudad, tenemos que empezar por ELLOS. Lo que no reciben en sus primeros meses de vida, ya sea falta de estímulos, alimentos o amor, no lo recuperan más. Vamos a ampliar el programa 'Primeros Meses' que garantiza asistencia médica y ayuda económica para las madres en situaciones de vulnerabilidad. Además, nos comprometemos a llegar a los 100 Centros de Primera Infancia. Ellos van a seguir siendo nuestra prioridad. No desde las palabras, sino desde la acción, con cambios que realmente mejoren su calidad de vida.", temas.DERECHOS_HUMANOS, 1, 0),

**Comment by felipemuni** [comment]
Gabriela Michetti

Propuesta("Programa de terrazas verdes", "", temas.MEDIO_AMBIENTE, 1, 1),

**Comment by felipemuni** [comment]
Martin Lousteau

Propuesta("Sanciones a las empresas de basura", "Controlar y penalizar a las empresas de recolección que no cumplan con sus obligaciones.", temas.MEDIO_AMBIENTE, 2, 0),
Propuesta("Profesionalizar a las cooperativas de recicladores urbanos", "", temas.MEDIO_AMBIENTE, 2, 0),
Propuesta("Cumplir la ley de basura cero", "", temas.MEDIO_AMBIENTE, 2, 0),
Propuesta("Reducir residuos no renovables", "Reducir los residuos no renovables mediante incentivos impositivos y normativas especiales.", temas.MEDIO_AMBIENTE, 2, 0),
Propuesta("Capacitar e incentivar a separar los residuos en cada casa", "", temas.MEDIO_AMBIENTE, 2, 0),
Propuesta("Recolección diferenciada", "Establecer de forma obligatoria la recolección diferenciada de residuos.", temas.MEDIO_AMBIENTE, 2, 0),

Propuesta("Cuida-Coches", "Regular la actividad de cuida-coches con registro y tarifa única como en Uruguay.", temas.SOCIEDAD, 2, 0),
Propuesta("Venta en la vía pública", "Regular la venta legal en la vía pública creando espacios especiales para la venta.", temas.SOCIEDAD, 2, 0)

Propuesta("Incentivos y protección para los denunciantes de corrupción", "", temas.INSTITUCIONAL, 2, 0),
Propuesta("Modificación de las normas para reducir la discrecionalidad en las compras y contrataciones", "", temas.INSTITUCIONAL, 2, 0),

**Comment by felipemuni** [comment]
Graciela Ocaña

Propuesta("Creación de una línea de créditos para familias jóvenes", "", temas.VIVIENDA, 2, 1),
Propuesta("Sistema de Garantías", "Modernización del sistema de garantías, reemplazando la garantía propietaria por el seguro de caución.", temas.VIVIENDA, 2, 1),
Propuesta("Instituto de la Vivienda de la Ciudad", "Gestión transparente y eficiente de los recursos del Instituto de la Vivienda de la Ciudad.", temas.VIVIENDA, 2, 1),
Propuesta("Cumplimiento de la ley de Basura Cero", "", temas.MEDIO_AMBIENTE, 2, 1),
Propuesta("Programa para la concientización de la separación en origen", "", temas.MEDIO_AMBIENTE, 2, 1),
Propuesta("ABL", "Reducción del ABL para vecinos que adhieran al Programa Hogares Verdes, separando la basura en el hogar.", temas.MEDIO_AMBIENTE, 2, 1),
Propuesta("Creación del programa de vecinos veedores voluntarios", "", temas.MEDIO_AMBIENTE, 2, 1),

**Comment by felipemuni** [comment]
Andrés Borthagaray

Propuesta("Vivienda social como parte global de la estrategia de desarrollo.", "", temas.VIVIENDA, 2, 2),
Propuesta("Hábitat:", "Derecho a una vivienda digna que no sea inalcanzable para la mayoría.", temas.VIVIENDA, 2, 2),
Propuesta("Utilizar las regulaciones edilicias y los terrenos disponibles para potenciar la vivienda social.", "", temas.VIVIENDA, 2, 2),
Propuesta("Políticas crediticias concretas que faciliten el acceso a la primera vivienda.", "", temas.VIVIENDA, 2, 2),
Propuesta("Promoción de las cooperativas de vivienda.", "", temas.VIVIENDA, 2, 2),
Propuesta("Plan de financiamiento de vivienda", "Incluidas propuestas específicas para la población más joven y la clase media.", temas.VIVIENDA, 2, 2),
Propuesta("Políticas de igualdad de género:", "Gabinete social y plan de igualdad de oportunidades que comprenda a todos las áreas de gobierno. ", temas.DERECHOS_HUMANOS, 2, 2),
Propuesta("Políticas para los jóvenes:", "Mayor desarrollo deportivo barrial, integración e inclusión en proyectos educativos, informáticos y productivos que les posibiliten mejores oportunidades laborales.", temas.DERECHOS_HUMANOS, 2, 2),
Propuesta("Violencia contra la mujer", "Políticas activas para prevenir y erradicar la violencia contra la mujer y todo tipo de violencia y discriminación institucional que se funde en los valores de la solidaridad y convivencia democrática.", temas.DERECHOS_HUMANOS, 2, 2),
Propuesta("Inclusión de los adultos mayores:", "Como ciudadanos activos la ciudad debe valorar su potencial e integrarlos como sujetos y no como meros espectadores. Adaptación de infraestructuras, complemento de planes de salud, oferta urbana en general.", temas.DERECHOS_HUMANOS, 2, 2),
Propuesta("Hacer de la coordinación de las fuerzas de policía una oportunidad de reforma y modernización.", "", temas.SEGURIDAD, 2, 2),
Propuesta("Facilitar el acceso a la justicia, desburocratizar el funcionamientoen el desarrollo de la jurisdicción local.", "", temas.SEGURIDAD, 2, 2),
Propuesta("Articulación con una política federal contra la droga y el narcotráfico.", "", temas.SEGURIDAD, 2, 2),
Propuesta("Potenciar los programas de probation", "", temas.SEGURIDAD, 2, 2),
Propuesta("Cambio cultural", "Como en Bogotá, para tratar la violencia. La ciudad no se transforma exclusivamente desde el Gobierno, sino también desde las actitudes de los ciudadanos. Algunas medidas: la promoción de formas no violentas de manifestación, otro tipo de festejos de fin de año, una cultura del fútbol más festiva y menos violenta, etc.", temas.SEGURIDAD, 2, 2),

**Comment by felipemuni** [comment]
Gustavo Vera

Propuesta(" Incorporar al mercado los 370 mil inmuebles ociosos para abaratar el precio de los alquileres.","", temas.VIVIENDA, 5, 0),
Propuesta("Cobrar un impuesto progresivo a los grandes propietarios de viviendas ociosas que no las destinen a alquilar para aumentar el fondo destinado a créditos hipotecarios.","", temas.VIVIENDA, 5, 0),
Propuesta(" Flexibilizar los requisitos de acceso al crédito hipotecario para que cualquier familia trabajadora pueda tener una vivienda. Incrementar el presupuesto del IVC destinado a viviendas sociales.","", temas.VIVIENDA, 5, 0),
Propuesta(" Urbanizar integralmente las villas construyendo solo una vivienda por familia a pagar en cuotas, hospitales, escuelas y servicios básicos.","", temas.VIVIENDA, 5, 0),

**Comment by felipemuni** [comment]
Claudio Lozano

Propuesta("Fortalecimiento de la producción de vivienda a través de formas cooperativas, autogestionarias y de empresas estatales.", "", temas.VIVIENDA, 8, 0),
Propuesta("Banco de inmuebles públicos y recuperación de tierras de la ciudad en manos del Estado Nacional para la asignación social.", "", temas.VIVIENDA, 8, 0),
Propuesta("Creación de una defensoría de inquilinos.", "", temas.VIVIENDA, 8, 0),
Propuesta("Relanzamiento de la Ley de Emergencia Habitacional para evitar desalojos.","", temas.VIVIENDA, 8, 0),

**Comment by felipemuni** [comment]
Myriam Bregman

Propuesta('Que todo legislador, funcionario estatal o juez gane lo mismo que un obrero especializado o un maestro','Que todo legislador, funcionario estatal o juez gane lo mismo que un obrero especializado o un maestro. Revocabilidad de todos los mandatos por los propios electores. Abolición del Senado y de la institución presidencial con poderes de monarca. Por una cámara única, con miembros elegidos utilizando el conjunto del país como distrito único.',temas.INSTITUCIONAL, 9,0),
Propuesta('Que se ponga fin a los privilegios de los jueces','Que se ponga fin a los privilegios de los jueces, como la inmovilidad en sus cargos y las exenciones impositivas. Que todo juez gane lo mismo que un docente. Que cesen en sus cargos todos los jueces en funciones que juraron por el estatuto de la dictadura. No al Consejo de la magistratura y a al actual método de designación de los magistrados. Que los jueces sean elegidos por el voto popular. Que sus cargos puedan ser revocados por sus electores.',temas.INSTITUCIONAL, 9,0),

**Comment by fvilledary** [comment]
Arreglado

**Comment by felipemuni** [comment]
Hector Bidonde

Propuesta("Más verde, menos cemento","Aumento de los espacios verdes. Basta de cementación especulativa y shoppings de IRSA, que agravan los efectos de las inundaciones. Defensa de la Reserva Ecológica. Plan progresivo de veredas verdes. Servicio de basura eficiente y público, sin negocio privado.", temas.MEDIO_AMBIENTE, 3, 0),
Propuesta("No más Cromañón ni Iron Mountain.","Lucro empresarial + no control estatal = corrupción y muerte. Estricto control público de todas las obras y habilitaciones, con participación comunal y social. Reincorporación de los profesionales verificadores de obra. Defensa del cuerpo de inspectores del trabajo.", temas.INSTITUCIONAL, 3, 0),
Propuesta("Ni una muerta más, ni una mujer menos.","Contra la violencia de género: abrir un refugio en cada Comuna, asistencia jurídica y psicológica gratuita, y subsidios de reinserción habitacional y laboral a las mujeres víctimas. Ninguna traba a los abortos no punibles; por el derecho al aborto. Cupo electoral del 50%.", temas.DERECHOS_HUMANOS, 3, 0),

**Comment by felipemuni** [comment]
Lousteau

Propuesta("Presupuesto", "Aumentar y ejecutar la totalidad del presupuesto destinado a vivienda.", temas.VIVIENDA, 2, 0),
Propuesta("Préstamos", "Subsidiar la tasa de interés para entregar 3800 préstamos al año con una tasa de un dígito. Reducir a la mitad el ingreso requerido para acceder al préstamo privilegiando la primera casa.", temas.VIVIENDA, 2, 0),
Propuesta("Urbanización", "Priorizar la integración en la urbanización duplicando la participación del gasto en vivienda.", temas.VIVIENDA, 2, 0),
