### ISSUE TITLE
Metodología de recopilación

### ISSUE THREAD

**Issue by juandimaio** [DemocraciaEnRed/vos-que-propones#8]
Hay que arreglar el recuadro que informa sobre la metodología. La info no entra; así que podríamos habilitar scrolling ahí o redimensionar el recuadro y tamaño de fuente. Puede que sea un problema de responsive o no, en la computadora la información se ve asi:
![captura de pantalla](https://cloud.githubusercontent.com/assets/11971050/7336020/408f777a-ebbc-11e4-96da-8cbe3baf999f.jpg)

**Comment by ignacionelson** [comment]
Estaría bueno aclarar ahí lo mismo que está en el readme (el orden es aleatorio cada vez que se genera la página)

**Comment by fvilledary** [comment]
Ya está agregado

**Comment by fvilledary** [comment]
Y Juan Cruz, ya arreglé un poco el tema de que no se vea el contenido. Fijate si ahora lo podés ver todo.
