### ISSUE TITLE
Subir o editar propuestas

### ISSUE THREAD

**Issue by juandimaio** [DemocraciaEnRed/vos-que-propones#9]
Gracias al feedback que tuvimos en el Grupo-PDR de fb, coincido en crear un sistema para subir propuestas o editar existentes; permitiendo agregar información y enriquecer el sitio. Debería incluir un campo obligatorio donde se requiera la fuente de donde se extrajo dicha propuesta. 
Aún así abro el debate ante la complejidad del asunto, para no terminar teniendo propuestas erróneas.

**Comment by gvilarino** [comment]
Para mí no debería ser algo que te permita directamente subir propuestas sino sugerir propuestas para un candidato X y que quede a revisión del equipo; si no se puede llenar rápidamente de cosas que no son ciertas.

**Comment by fvilledary** [comment]
Coincido con Guido. Viendo el comportamiento de las personas en otras páginas, el poder agregar propuestas va a ser muy perjudicial para la página, ni siquiera comentarios pondría, porque podrían sacarle la importancia a la propuesta en si.
En un momento pensamos en poner a disposición un formulario de google para agregar propuestas y luego nosotros agregarlas si eran correctas, pero después nos pusimos más rigurosos con el tema de agregar propuestas, dando como válidas solo las que aparecían en sitios web oficiales de los candidatos, por lo que no tendría sentido que cualquiera te escriba una en un formulario.

**Comment by gvilarino** [comment]
A fines prácticos, que pongas un `mailto` o bien un link a un `gitter` o algo similar alcanza y sobra. No debería ser que se use más de X veces para completar las propuestas que faltan. Laburar mucho para algo que casi no va a ser usado me parece overkill en esta etapa. Quizás después de estas elecciones si alguien tiene ganas tendría sentido pero ahora somos pocos y hay mucho por hacer.

**Comment by ramasilveyra** [comment]
El sistema para crear y editar propuestas, candidatos y partidos esta hecho. Solo falta lo del campo fuente para las propuestas: [Fuentes #11](https://github.com/PartidoDeLaRed/queproponen/issues/11). Se debe cerrar esta issue?
